vae_refgpc_home:
    path:     /{base}
    defaults:
       _controller: vaeRefGPCBundle:Accueil:index
       base:    MP
    requirements: 
       base:   LR|MP|AD
    
vae_refgpc_ilot:
    path:     /{base}/ilot
    defaults:
       _controller: vaeRefGPCBundle:Ilot:index
       base:    MP
    requirements: 
       base:   LR|MP|AD
 
vae_refgpc_ilotRecherche:
    path: /{base}/ilot/recherche
    defaults:
       _controller: vaeRefGPCBundle:Ilot:ajaxIlotRecherche
       base: MP
    requirements:
        _method: POST
        base:   LR|MP|AD
        
vae_refgpc_centre:
    path:     /{base}/centre
    defaults:
       _controller: vaeRefGPCBundle:Ilot:index
       base:    MP
    requirements: 
       base:   LR|MP|AD
       

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    path:      /AD/connexion
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

fos_user_security_logout:
    path:      /AD/deconnexion
    defaults:  { _controller: FOSUserBundle:Security:logout, _method: POST }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /AD/profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile